=== six3six/Zuul/Test/TestFile.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="TestFile" >
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="TestOp" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
            <xs:attribute name="useInitialState" type="xs:boolean" default="false" />
        </xs:complexType>
    </xs:element>



    <xs:element name="TestOp">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Command" type="xs:string" />
                <xs:element name="Return" type="xs:string" />
                <xs:element type="xs:boolean" name="CheckReturn"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== six3six/Zuul/Test/long.xml
<?xml version="1.0" encoding="UTF-8"?>
<TestFile useInitialState="true" xs:noNamespaceSchemaLocation="TestFile.xsd"  xmlns:xs="http://www.w3.org/2001/XMLSchema-instance">
    <TestOp>
        <Command>manger</Command>
        <Return></Return>
        <CheckReturn>false</CheckReturn>
    </TestOp>

    <TestOp>
        <Command>aller nord</Command>
        <Return>test</Return>
        <CheckReturn>true</CheckReturn>
    </TestOp>
</TestFile>
